// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv4BPWY9kEsGUk8j282Ch6jaI91vC9xOY',
    appId: '1:202094225926:web:8168541fb27059b414b187',
    messagingSenderId: '202094225926',
    projectId: 'society-management-app-a808b',
    authDomain: 'society-management-app-a808b.firebaseapp.com',
    storageBucket: 'society-management-app-a808b.firebasestorage.app',
    measurementId: 'G-FWGRL2LW4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmFGRGQlbmFBtKRIev8XsrgYsBGTgSI_U',
    appId: '1:202094225926:android:3baa22da11eec4de14b187',
    messagingSenderId: '202094225926',
    projectId: 'society-management-app-a808b',
    storageBucket: 'society-management-app-a808b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbCfwmCjAt5tN6xLQP9rVDMGClu4r2ziA',
    appId: '1:202094225926:ios:15bcef935700116e14b187',
    messagingSenderId: '202094225926',
    projectId: 'society-management-app-a808b',
    storageBucket: 'society-management-app-a808b.firebasestorage.app',
    iosBundleId: 'com.society.societyManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbCfwmCjAt5tN6xLQP9rVDMGClu4r2ziA',
    appId: '1:202094225926:ios:15bcef935700116e14b187',
    messagingSenderId: '202094225926',
    projectId: 'society-management-app-a808b',
    storageBucket: 'society-management-app-a808b.firebasestorage.app',
    iosBundleId: 'com.society.societyManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv4BPWY9kEsGUk8j282Ch6jaI91vC9xOY',
    appId: '1:202094225926:web:c2c0ae396c83ae5c14b187',
    messagingSenderId: '202094225926',
    projectId: 'society-management-app-a808b',
    authDomain: 'society-management-app-a808b.firebaseapp.com',
    storageBucket: 'society-management-app-a808b.firebasestorage.app',
    measurementId: 'G-1E31BNWXP2',
  );
}
